- src/lib.rs
- src/reader/geometry.rs
- src/reader/geometry_collection.rs
- src/reader/mod.rs
- src/writer/mod.rs
With this PR, the only exposed read API is
```
wkb::reader::read_wkb
```
which returns an `impl geo_traits::GeometryTrait`. Ideally we'll never need to expose more detailed APIs!
> Cleaner public read API

- Cargo.toml
It turns out that the minimum rust version is actually 1.82 (given the `use<'_>` syntax in `read_wkb`)
Check with:
```
rustup install 1.81.0
rustup run 1.81.0 cargo build
```
gives:
```
error[E0658]: precise captures on `impl Trait` are experimental
--> src/reader/mod.rs:33:63
|
33 | pub fn read_wkb(buf: &[u8]) -> WKBResult<impl GeometryTrait + use<'_>> {
|                                                               ^^^
|
= note: see issue #123432 <https://github.com/rust-lang/rust/issues/123432> for more information
```
> Update minimum rust version

- src/reader/mod.rs
Edit the return type of `read_wkb` to indicate that the returned geometry has type `T=f64`.
> Return f64 geometry

- src/common.rs
- src/reader/geometry.rs
- src/writer/geometrycollection.rs
- src/writer/linestring.rs
- src/writer/multilinestring.rs
- src/writer/multipoint.rs
- src/writer/multipolygon.rs
- src/writer/point.rs
- src/writer/polygon.rs
> Support reading and writing m and zm

- src/common.rs
- src/writer/polygon.rs
> Avoid panic when writing empty polygon

- src/writer/geometry.rs
- src/writer/geometrycollection.rs
- src/writer/line.rs
- src/writer/linestring.rs
- src/writer/mod.rs
- src/writer/multilinestring.rs
- src/writer/multipoint.rs
- src/writer/multipolygon.rs
- src/writer/polygon.rs
- src/writer/triangle.rs
---
These are written to WKB as LineString and Polygon, respectively.
> Add support for writing Line and Triangle geometries

- src/reader/polygon.rs
- src/writer/coord.rs
- src/writer/geometry.rs
- src/writer/geometrycollection.rs
- src/writer/linestring.rs
- src/writer/multilinestring.rs
- src/writer/multipoint.rs
- src/writer/multipolygon.rs
- src/writer/point.rs
- src/writer/polygon.rs
---
Use `&mut impl Write` instead of adding a new `W: Write` generic
> Inline trait bound for writer

- benches/parse.rs
---
Previously the bench to parse was 
This is **2.3x faster** than `shapely.wkb.loads`, and 11x faster than `shapely.wkb.dumps`! There's probably a tiny bit of Python overhead on the shapely side (e.g. an extra full-buffer copy back to Python after GEOS has serialized the geometry to a buffer) but I expect this is still at least a little faster than GEOS.
```
parse big to geo        time:   [161.29 µs 161.83 µs 162.38 µs]
change: [-1.0724% -0.4549% +0.1358%] (p = 0.15 > 0.05)
encode big              time:   [49.969 µs 50.204 µs 50.437 µs]
```
```py
from shapely import wkt, wkb
with open('big.wkt') as f:
geom = wkt.load(f)
%timeit buf = wkb.dumps(geom)
%timeit test = wkb.loads(buf)
```
> Add benches w/ copy to geo geometry & encoding

- src/reader/coord.rs
- src/reader/linearring.rs
- src/reader/polygon.rs
---
It turns out function inlining can have a surprisingly big effect on the benchmark:
```
Benchmarking parse small to geo: Collecting 100 samples in estimated 5.0001 s (42M itera
parse small to geo      time:   [125.30 ns 125.89 ns 126.34 ns]
change: [-12.615% -11.585% -10.646%] (p = 0.00 < 0.05)
Performance has improved.
Benchmarking parse big to geo: Collecting 100 samples in estimated 5.2794 s (40k iterati
parse big to geo        time:   [130.44 µs 131.96 µs 133.69 µs]
change: [-16.388% -15.530% -14.647%] (p = 0.00 < 0.05)
Performance has improved.
Found 18 outliers among 100 measurements (18.00%)
16 (16.00%) low mild
2 (2.00%) high severe
```
That brings the parse to 2.8x faster than `shapely.wkb.loads` (see #37)
> Add some function inlining

- src/common.rs
- src/lib.rs
- src/test.rs
- src/writer/geometrycollection.rs
- src/writer/linestring.rs
- src/writer/point.rs
- src/writer/polygon.rs
> Add 2d tests

- CHANGELOG.md
- Cargo.toml
- README.md
---
- Bump version to 0.8
- Creates `CHANGELOG.md`
> Prepare release 0.8

- Cargo.toml
> Bump geos version to fix tests

- CHANGELOG.md
- src/reader/geometry.rs
- src/reader/geometry_collection.rs
- src/reader/linestring.rs
- src/reader/multilinestring.rs
- src/reader/multipoint.rs
- src/reader/multipolygon.rs
- src/reader/polygon.rs
- src/test/wkb.rs
---
I found that the lifetime annotations of various geo-traits implementations for WKB geometry types are unnecessarily restrictive. For instance:
```rust
fn lifetime() {
let buf = vec![
1,                      // little endian byte order
1, 0, 0, 0,             // wkbPoint (type 1)
0, 0, 0, 0, 0, 0, 240, 63, // X coordinate (1.0)
0, 0, 0, 0, 0, 0, 0, 64,   // Y coordinate (2.0)
];
let coord;
{
let wkb = read_wkb(&buf).unwrap();
let wkb_ref = &wkb;
let wkb_ref_ref = &&wkb_ref;
match wkb_ref_ref.as_type() {
geo_traits::GeometryType::LineString(line_string) => {
coord = line_string.coord(0);
}
_ => {
panic!("Expected LineString");
}
}
};
assert!(coord.is_some());
assert_eq!(coord.unwrap().x(), 1.0);
assert_eq!(coord.unwrap().y(), 2.0);
}
```
fails to compile. `coord` should be valid since …
> Fix lifetime annotations for various implementations of geo traits

- CHANGELOG.md
- src/reader/geometry.rs
- src/test/wkb.rs
---
Just found another overly restrictive lifetime annotation in the specialized implementation of GeometryTrait for geometry types other than `Wkb`. The newly added test case fails without this patch:
```
error[E0597]: `wkb` does not live long enough
--> src/test/wkb.rs:190:15
|
188 |     let coord = {
|         ----- borrow later stored here
189 |         let wkb = read_wkb(&buf).unwrap();
|             --- binding `wkb` declared here
190 |         match wkb.as_type() {
|               ^^^ borrowed value does not live long enough
...
205 |     };
|     - `wkb` dropped here while still borrowed
For more information about this error, try `rustc --explain E0597`.
```
> Fix the lifetime annotation of specialized implementation of GeometryTrait

- CHANGELOG.md
- src/common.rs
- src/error.rs
- src/lib.rs
- src/reader/coord.rs
- src/reader/geometry.rs
- src/reader/geometry_collection.rs
- src/reader/linearring.rs
- src/reader/linestring.rs
- src/reader/mod.rs
- src/reader/multilinestring.rs
- src/reader/multipoint.rs
- src/reader/multipolygon.rs
- src/reader/point.rs
- src/reader/polygon.rs
- src/reader/util.rs
- src/writer/coord.rs
- src/writer/geometry.rs
- src/writer/geometrycollection.rs
- src/writer/line.rs
- src/writer/linestring.rs
- src/writer/multilinestring.rs
- src/writer/multipoint.rs
- src/writer/multipolygon.rs
- src/writer/point.rs
- src/writer/polygon.rs
- src/writer/rect.rs
- src/writer/triangle.rs
---
Closes https://github.com/georust/wkb/issues/56
We already had `Wkb` in the public API. I think it would be best if we standardized on `Wkb` as a consistent spelling.
- `WKBResult` is now `WkbResult`.
- `WKBError` is now `WkbError`.
- (not public) `WKBDimension` is now `WkbDimension`.
- (exported but impossible to use because WkbDimension is private 🙈 #48) `WKBType` is now `WkbType`.
- (not public) `WKBLinearRing` is now `LinearRing`
> Standardize capitalization of `WKB` as `Wkb`

- CHANGELOG.md
- src/common.rs
- src/reader/coord.rs
- src/reader/geometry.rs
- src/reader/geometry_collection.rs
- src/reader/linearring.rs
- src/reader/linestring.rs
- src/reader/mod.rs
- src/reader/multilinestring.rs
- src/reader/multipoint.rs
- src/reader/multipolygon.rs
- src/reader/point.rs
- src/reader/polygon.rs
---
- add `dimension` and `geometry_type` methods to `Wkb`
- Add `GeometryType` enum
- Rename `WKBDimension` to `Dimension`
Closes https://github.com/georust/wkb/issues/58, closes https://github.com/georust/wkb/issues/60
> Expose `GeometryType` and `Dimension` from parsed `Wkb` object

- Cargo.toml
- benches/brect.rs
- benches/parse.rs
---
The `wkt` crate is currently only used in the two benchmarking scripts.
- Bump `wkt` to 0.13
- Add `geo-types` feature to avoid using the geo-traits APIs of the `wkt` crate. This means we can independently bump the version of `geo-traits` here in `wkb` separately from in `wkt`.
> Bump `wkt` dev dependency to 0.13

- CHANGELOG.md
- src/common.rs
- src/reader/geometry.rs
- src/reader/geometry_collection.rs
- src/reader/linearring.rs
- src/reader/linestring.rs
- src/reader/multilinestring.rs
- src/reader/multipoint.rs
- src/reader/multipolygon.rs
- src/reader/point.rs
- src/reader/polygon.rs
- src/reader/util.rs
- src/test/invalid_ewkb.rs
- src/test/invalid_wkb.rs
- src/test/mod.rs
---
There are lots of usages of `.unwrap` in the constructors of WKB geometry values, this will make the program panic when parsing invalid geometries. Properly handling invalid WKB without panicking should be a very basic feature of georust/wkb since the user of this crate may want to handle or recover from input errors instead of panicking, so we submit this PR to return `Err` to give the caller of `Wkb::try_new` a chance to handle the error.
This PR should have minimal impact on the API, since `Wkb::try_new` already returns a `Result<..>`. This PR just propagates the errors to the return value instead of panicking inside of `try_new`. The performance of WKB parsing will be slightly affected. However, the typical workload dealing with parsed Wkb values involves traversing the …
> Don't panic when parsing invalid WKB using `Wkb::try_new`

- CHANGELOG.md
- src/lib.rs
- src/reader/mod.rs
---
Closes https://github.com/georust/wkb/issues/73
Exposes the `Dimension` enum as `wkb::reader::Dimension`. This is only relevant to reader code as write APIs will access the dimension from geo-traits
> Expose `Dimension` publicly

- CHANGELOG.md
- src/writer/line.rs
- src/writer/rect.rs
- src/writer/triangle.rs
---
Rust 1.90 caused a regression in release mode for consumers of the `geoarrow-array` crate: https://github.com/geoarrow/geoarrow-rs/issues/1339, https://github.com/rust-lang/rust/issues/131960. This code compiled fine in 1.89 but no longer compiles in 1.90 in release mode. (It compiles in debug mode)
I tracked this down to the trait wrappers implemented here. If you pull main of `geoarrow-rs` (https://github.com/geoarrow/geoarrow-rs/commit/338a08cd2f5f2b35df36453ec3ad6ef031dfb702) and run `cargo +1.90 build --release -p geoarrow-array` you get a compiler error. If you check out the branch in https://github.com/geoarrow/geoarrow-rs/pull/1341 you no longer get a compiler error.
Perhaps we should add some docs to the code to explain why we're not using trait wrappers? Then again, this …
> fix: Remove trait wrappers to work around Rust 1.90 compiler regression

- CHANGELOG.md
- src/common.rs
- src/reader/coord.rs
- src/reader/geometry.rs
- src/reader/geometry_collection.rs
- src/reader/linearring.rs
- src/reader/linestring.rs
- src/reader/mod.rs
- src/reader/multilinestring.rs
- src/reader/multipoint.rs
- src/reader/multipolygon.rs
- src/reader/point.rs
- src/reader/polygon.rs
- src/test/wkb.rs
---
This work originates from [SedonaDB](https://github.com/apache/sedona-db). We have implemented a fast WKB to GEOS geometry conversion function in our own fork of wkb: https://github.com/wherobots/wkb/pull/2, which requires access to the underlying WKB buffer and structs defined for individual geometry types. Having access to these implementation details allows us to make this particular task 4 times faster.
I believe that there might be other scenarios where having access to the raw WKB buffer will help a lot, so I added several methods for exposing slices of WKB buffers and some metadata about the encoded coordinates.
> Expose APIs for accessing the underlying WKB buffer to implement various functions efficiently
